#PREFIXO DAS MENSAGENS
Prefix: '&6&lWAVEMC:'


#COORDENADAS DE PROTEÇÃO DO SPAWN
#PERGUNTE AO DESENVOLVEDOR PARA ELE TE AJUDAR COM ISSO
SpawnProtecaoZ1: 6756
SpawnProtecaoZ2: 6807
SpawnProtecaoX1: 6254
SpawnProtecaoX2: 6276


SpawnAltura: 142

#ALTURA MAXIMA QUE PODE PUXAR PRO GLAD
GladAltura: 142

words:
  - sopa bugada
  - a sopa esta bugada
  - bugou a sopa
  - sopa bug
  - bug da sopa voltou
  - sopa esta bug
  - sopa está bug
  - adm a sopa bugou
  - pq a sopa volta pro inv
  - porque a sopa volta pro inv
  - sopa fica voltando

#Nome do vidro da loja de kits
ShopItem: '&cCompre kits aqui'

LojaInv: '&bLoja de kits'

WarpsInv: '&aWarps'

StatusInv: '&aSeu Perfil'



#Cooldown dos Kits
GrapplerCooldown: 4
JumperCooldown: 25
ThorCooldown: 5
NinjaCooldown: 10
MilkManCooldown: 15
ScoutCooldown: 40
SwitcherCooldown: 7
TimeLordCooldown: 30
TornadoCooldown: 60

#EDITE NOME DOS RANKS SE QUISER
GodRank: 'GOD'
LendarioRank: 'Lendário'
RubyRank: 'Ruby'
SafiraRank: 'Safira'
CristalRank: 'Cristal'
EsmeraldaRank: 'Esmeralda'
DiamanteRank: 'Diamante'
OuroRank: 'Ouro'
PrataRank: 'Prata'
VeteranoRank: 'Veterano'
ExperienteRank: 'Experiente'
AvancadoRank: 'Avançado'
InicianteRank: 'Iniciante'
UnrankedRank: 'Unranked'

#REQUISITOS DE KILLS PARA RANK
InicianteKills: 100
AvancadoKills: 300
ExperienteKills: 600
VeteranoKills: 850
PrataKills: 1200
OuroKills: 1500
DiamanteKills: 2200
EsmeraldaKills: 3000
CristalKills: 4200
SafiraKills: 5000
RubyKills: 6300
LendarioKills: 7500
GodKills: 10000




#EDITE O IP QUE FICA NA SCOREBOARD AQUI
IPScore: 'wavemc.com'



#MENSAGEM DO REQ DE YOUTUBER MENU DO /youtuber
MSGYT1: '&f* 100 visualizações'
MSGYT2: '&f* 10 likes'
MSGYT3: '&f* Vídeo no Servidor'

#MENSAGEM DO REQ DE STREAMER DO MENU DO /youtuber
MSGSTREAMER1: '&f* 50 seguidores'
MSGSTREAMER2: '&f* 5 telespectadores'
MSGSTREAMER3: '&f* Fazer live a cada 15 dias'

#REGRAS
REGRA1: '&e* &cProibido usar trapa�as ou cheats.'
REGRA2: '&e* &cProibido Divulgar outros Servidores.'
REGRA3: '&e* &cProibido Assédio.'
REGRA4: '&e* &cProibido Abusar de Erros ou Bugs.'
REGRA5: '&e* &cProibido Xingar jogadores.'
REGRA6: '&e* &cProibido Xingar a Staff ou Servidor.'
REGRA7: '&e* &cProibido Chat Fake.'

#LORE DOS KITS
NenhumLore: 'Sem habilidade'
PvPLore: 'Ganhe espada afiada 1'
AntiStomperLore: 'Seja imune a stompers'
JumperLore: 'Voe com sua enderpearl'
KangarooLore: 'De pulos duplos'
ThorLore: 'Solte raios'
ArcherLore: 'Ganhe arco e flecha'
NeoLore: 'Imune a varios kits'
QuickDropperLore: 'Drope potes automaticamente'
StomperLore: 'Esmague seus inimigos'
FishermanLore: 'Pesque players'
AnchorLore: 'Não de nem receba KB'
TornadoLore: 'Crie um tornado'
ViperLore: 'De veneno ao hitar'
SnailLore: 'De lentidao ao hitar'
PoseidonLore: 'Ganhe efeitos na agua'
FiremanLore: 'De fogo ao hitar'
NinjaLore: 'Aperte SHIFT e teleporte ao inimigo'
GrapplerLore: 'Corra por ai com sua corda'
TimelordLore: 'Pare o tempo'
MonkLore: 'Embaralhe o inventario do inimigo'
StomperLore: 'Esmague seus inimigos'
LeechLore: 'Roube a vida dos inimigos'
CamelLore: 'Ganhe efeitos em desertos'
GrandpaLore: 'De muito KB!'
ScoutLore: 'Ganhe velocidade'
CriticalLore: 'De danos criticos'
MilkmanLore: 'Beba leite e fique forte'
TurtleLore: 'Aperte SHIFT e leve menos damage'
PhantomLore: 'Voe com seu kit'
BoxerLore: 'Seja um boxeador'
HulkLore: 'Pegue os inimigos nas costas'
SwitcherLore: 'Troque de lugar com o inimigo'
GladiatorLore: 'Puxe seu inimigo para uma arena particular'


Anchor2Lore: 'Não de nem receba KB'
Kangaroo2Lore: 'De pulos duplos'
Grappler2Lore: 'Corra por ai com sua corda'

#TEMPO DO FEAST (EM MINUTOS)
TempoFeast: 5

#MUNDO DO BAU DO FEAST
FeastWorld: 'spawn'

#LOCAIS DOS BAUS DO FEAST (ALTERE SE QUISER)
Bau1X: -41.0
Bau1Y: 121.0
Bau1Z: 325.0

Bau2X: -44.0
Bau2Y: 121.0
Bau2Z: 328.0

Bau3X: -44.0
Bau3Y: 121.0
Bau3Z: 322.0

Bau4X: -47.0
Bau4Y: 121.0
Bau4Z: 325.0

Bau5X: -8.590
Bau5Y: 112.00000000
Bau5Z: 252.246

Bau6X: -12.384
Bau6Y: 112.00000 
Bau6Z: 249.451

Bau7X: -8.492
Bau7Y: 112.00000 
Bau7Z: 245.762

Bau8X: -4.549 
Bau8Y: 112.00000 
Bau8Z: 249.694

#VAI CAIR UM RAIO NESSE LOCAL QUANDO O FEAST NASCER
RaioX: -44.630
RaioY: 120.75000 
RaioZ: 352.392

#N�O MEXA NISSO SE NAO VAI FUDER COM O PLUGIN!
#E ELE NAO VAI MAIS LIGAR
#VOCE FOI AVISADO
ab: 163.123.204.170
ab2: 3306
ac: s3055_bot
ad: u3055_SyyUanevTm
ae: sZlQ!x4Y3!Z.w^LiBFPj8ECe

#PRE�O DOS KITS
#DEIXE 0 PARA DEIXAR O KIT GRATIS PARA JOGADOR NORMAL
#COLOQUE -1 NO PRE�O PARA DESATIVAR O KIT
PvPPrice: 0
KangarooPrice: 0
ThorPrice: 0
ArcherPrice: 0
NeoPrice: 0
QuickDropperPrice: 0
AntiStomperPrice: 0
FishermanPrice: 7000
AnchorPrice: 7000
TornadoPrice: 20000
ViperPrice: 5000
SnailPrice: 6000
PoseidonPrice: 5000
FiremanPrice: 7000
NinjaPrice: 7000
GrapplerPrice: 15000
TimeLordPrice: 13000
MonkPrice: 7500
StomperPrice: 12500
LeechPrice: 11000
CamelPrice: 8000
GrandpaPrice: 10000
ScoutPrice: 10000
CriticalPrice: 14000
MilkmanPrice: 12500
TurtlePrice: 7000
PhantomPrice: 11000
BoxerPrice: 12000
HulkPrice: 11000
SwitcherPrice: 0
GladiatorPrice: 18000 
JumperPrice: 10000




